### ISSUE TITLE
Compiling FSM hangs

### ISSUE THREAD

**Issue by adamslc** [Azzaare/BibParser.jl#1]
Hi there!

I am working on a package to display citation information in package documentation, and as part of this, I need to parse `.bib` files. Rather than reinvent the wheel, I'm trying to use this package, but the call to`Automa.compile(bibfile)` is hanging. Was this a problem that you experienced when you were writing this package?

**Comment by Azzaare** [comment]
Hi,

Actually, the problem comes from the size of the automata generated. It is due to the recursive LaTeX code that can be included inside bib files.
I planned to take care of it in different ways, but I got lazy and waited for Julia 1.0 to be out and have the automa.jl package up-to-date and so on.

Are you in a rush? I can have a look next week. Also, if I fix this problem, I can probably publish the package.

**Comment by adamslc** [comment]
Thanks for the quick reply, and no rush. I wish I could be more help, but the parser code is way over my head...

The package I am working on is [here](https://github.com/adamslc/Citations.jl). In the short term, I've used `PyCall` and `bibtexparser`, but it would be great to replace that with a pure Julia solution.

**Comment by Azzaare** [comment]
Hmm, I have been totally overwhelmed by other tasks and I totally forgot about it ...
I have restarted this small project, and updated it to Julia 1.x

Compilation should not hang long (about 10 sec on my machine) ... if you ever have some interest in it

I plan to integrate a better parser (that is a complete BibTeX parser) eventually . In the meantime a few BibTeX syntax are not allowed ( I will write a README next week).
